In [22]:
!python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

Requirement already satisfied: python-woc in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: pandas in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from python-woc) (4.70.0)
Requirement already satisfied: anyio in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.12.1)
Requirement already satisfied: certifi in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (3.19)
Requirement already satisfied: h11>=0.16 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: numpy>=1.22.4 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.1)
Requirement already satisfied: six>=1.5 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /home/cfinley6/cosc445/venv/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.16.0)

In [23]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# My assigned projects
# - 'mpld3_mpld3'
# - 'nilmtk_nilmtk'
# - 'dellytools_delly'
# - 'bedops_bedops'
# - 'opencog_opencog'
# - 'mschauer_causalinference'
# - 'matwey_fips3'
# - 'neuralensemble_libneuroml'
# - 'benjjneb_dada2'
# - 'ngageoint_opensphere'

# Now for each of the ten projects you were assigned get commits, e.g.
projects = ['ngageoint_opensphere']
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

                                       sha1               project
0  0000b245ec6ef0930251d1efab26a5229976c38b  ngageoint_opensphere

In [24]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  1%|▏         | 20/1486 [00:20<25:27,  1.04s/it]

Got Errors {'0322eef4a5bdd9cd4822eb49e8850e45bb8cb835': 'Key 0322eef4a5bdd9cd4822eb49e8850e45bb8cb835 not found in /da5_fast/All.sha1c/commit_3.tch'}

  9%|▉         | 136/1486 [02:21<23:24,  1.04s/it]

Got Errors {'1620b72459b572a7c3bd562bc1dc748447c28495': 'Key 1620b72459b572a7c3bd562bc1dc748447c28495 not found in /da5_fast/All.sha1c/commit_22.tch'}

 10%|█         | 153/1486 [02:39<23:04,  1.04s/it]

Got Errors {'195e3ecae937dcc204e0b869197df9b8c99bd473': 'Key 195e3ecae937dcc204e0b869197df9b8c99bd473 not found in /da5_fast/All.sha1c/commit_25.tch'}

 11%|█▏        | 170/1486 [02:57<22:56,  1.05s/it]

Got Errors {'1cb09bac9fb0db1707e2e6e022b4ffb4c4417bba': 'Key 1cb09bac9fb0db1707e2e6e022b4ffb4c4417bba not found in /da5_fast/All.sha1c/commit_28.tch'}

 18%|█▊        | 272/1486 [04:43<21:01,  1.04s/it]

Got Errors {'2d5fcaa27ae9f3bc0232968085bf72050cc0b672': 'Key 2d5fcaa27ae9f3bc0232968085bf72050cc0b672 not found in /da5_fast/All.sha1c/commit_45.tch'}

 24%|██▍       | 357/1486 [06:11<19:34,  1.04s/it]

Got Errors {'3c13ff99a2563a792485d503c0b24f6cd3bc1018': 'Key 3c13ff99a2563a792485d503c0b24f6cd3bc1018 not found in /da5_fast/All.sha1c/commit_60.tch'}

 26%|██▌       | 384/1486 [06:39<19:03,  1.04s/it]

Got Errors {'400c47c09bb75be006df84cb916058928bad5fb7': 'Key 400c47c09bb75be006df84cb916058928bad5fb7 not found in /da5_fast/All.sha1c/commit_64.tch'}

 28%|██▊       | 409/1486 [07:05<18:41,  1.04s/it]

Got Errors {'44743cbf69e82cc3225a42f8ae34acbf4b949138': 'Key 44743cbf69e82cc3225a42f8ae34acbf4b949138 not found in /da5_fast/All.sha1c/commit_68.tch'}

 28%|██▊       | 416/1486 [07:13<18:30,  1.04s/it]

Got Errors {'45d1bd28abc3cf06c211ab3900893ac801c5b9a6': 'Key 45d1bd28abc3cf06c211ab3900893ac801c5b9a6 not found in /da5_fast/All.sha1c/commit_69.tch'}

 40%|███▉      | 590/1486 [10:14<15:36,  1.04s/it]

Got Errors {'6322a37f24ead63f2ee17f73dc94305ca6365f42': 'Key 6322a37f24ead63f2ee17f73dc94305ca6365f42 not found in /da5_fast/All.sha1c/commit_99.tch'}

 42%|████▏     | 629/1486 [10:55<14:56,  1.05s/it]

Got Errors {'6a40b00fca9df628836e9820829f85c949dc2172': 'Key 6a40b00fca9df628836e9820829f85c949dc2172 not found in /da5_fast/All.sha1c/commit_106.tch'}

 45%|████▌     | 671/1486 [11:38<14:06,  1.04s/it]

Got Errors {'71043562119c8d2d821e5165e0c96bd0fe78e19c': 'Key 71043562119c8d2d821e5165e0c96bd0fe78e19c not found in /da5_fast/All.sha1c/commit_113.tch'}

 48%|████▊     | 713/1486 [12:22<13:23,  1.04s/it]

Got Errors {'7863156fc97108adef9318f57e71dd9f4c98d286': 'Key 7863156fc97108adef9318f57e71dd9f4c98d286 not found in /da5_fast/All.sha1c/commit_120.tch'}

 49%|████▉     | 730/1486 [12:40<13:07,  1.04s/it]

Got Errors {'7b9fef27b50e39686a229fa2691ea17cf386e94f': 'Key 7b9fef27b50e39686a229fa2691ea17cf386e94f not found in /da5_fast/All.sha1c/commit_123.tch'}

 52%|█████▏    | 769/1486 [13:20<12:22,  1.04s/it]

Got Errors {'8208c43a7ed834167ccfd6d9c47c649a990a20e1': 'Key 8208c43a7ed834167ccfd6d9c47c649a990a20e1 not found in /da5_fast/All.sha1c/commit_2.tch'}

 57%|█████▋    | 844/1486 [14:38<11:12,  1.05s/it]

Got Errors {'8f3e2c3a042ad686c1e802b49b1f2a4e436ad768': 'Key 8f3e2c3a042ad686c1e802b49b1f2a4e436ad768 not found in /da5_fast/All.sha1c/commit_15.tch'}

 57%|█████▋    | 847/1486 [14:41<11:04,  1.04s/it]

Got Errors {'8fd7118a3ce6c0fb200d3faf9cd8b89dc53e1151': 'Key 8fd7118a3ce6c0fb200d3faf9cd8b89dc53e1151 not found in /da5_fast/All.sha1c/commit_15.tch'}

 78%|███████▊  | 1156/1486 [20:02<05:42,  1.04s/it]

Got Errors {'c59c1007b9ec1e821e558438871559c8c70c766c': 'Key c59c1007b9ec1e821e558438871559c8c70c766c not found in /da5_fast/All.sha1c/commit_69.tch'}

 82%|████████▏ | 1218/1486 [21:06<04:38,  1.04s/it]

Got Errors {'d066be0a732b430d1c3103726086930b36e58ab4': 'Key d066be0a732b430d1c3103726086930b36e58ab4 not found in /da5_fast/All.sha1c/commit_80.tch'}

 91%|█████████ | 1345/1486 [23:18<02:26,  1.04s/it]

Got Errors {'e6d39b4aed1fd164aa144b893f9e6c4cd7e36ca3': 'Key e6d39b4aed1fd164aa144b893f9e6c4cd7e36ca3 not found in /da5_fast/All.sha1c/commit_102.tch'}

 91%|█████████ | 1355/1486 [23:28<02:15,  1.04s/it]

Got Errors {'e8f784dcfaa56d4e7bdb1b7de99515948dd501e1': 'Key e8f784dcfaa56d4e7bdb1b7de99515948dd501e1 not found in /da5_fast/All.sha1c/commit_104.tch'}

 99%|█████████▉| 1478/1486 [25:36<00:08,  1.04s/it]

Got Errors {'fe69e1da384c733094e0cb489d73695cf8f4c0c5': 'Key fe69e1da384c733094e0cb489d73695cf8f4c0c5 not found in /da5_fast/All.sha1c/commit_126.tch'}

100%|██████████| 1486/1486 [25:44<00:00,  1.04s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0000b245ec6ef0930251d1efab26a5229976c38b,7ca74da9db702dd28af150248c5b9374a00f8cd4,[679ec891c90963dd56a89bb2245ac77b6a95950a],Glenn Kitchell <kitchellg@wudn-kitchellg.udev....,1607457593,-0700,Glenn Kitchell <kitchellg@wudn-kitchellg.udev....,1607457593,-0700,feat(featureinfo): improve column lookup\n\nup...,0000b245ec6ef0930251d1efab26a5229976c38b,ngageoint_opensphere
1,00052f288aaa70859ca3bdfcdd1f2c7285059233,b00556e87998ea67c6b7427402d5b1261da59d07,[c3159a9d9db64a313e5ea340b7516d5624838ca5],Damien Baca <bacad@wudn-intern4.udev.six3>,1606939645,-0700,Damien Baca <bacad@wudn-intern4.udev.six3>,1607017138,-0700,fix(nobreakspace): normalized whitespace for f...,00052f288aaa70859ca3bdfcdd1f2c7285059233,ngageoint_opensphere

In [25]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '0000b245ec6ef0930251d1efab26a5229976c38b', 'tree': '7ca74da9db702dd28af150248c5b9374a00f8cd4', 'parent': ['679ec891c90963dd56a89bb2245ac77b6a95950a'], 'author': 'Glenn Kitchell <kitchellg@wudn-kitchellg.udev.six3>', 'author_time': 1607457593, 'author_tz': '-0700', 'committer': 'Glenn Kitchell <kitchellg@wudn-kitchellg.udev.six3>', 'committer_time': 1607457593, 'committer_tz': '-0700', 'message': 'feat(featureinfo): improve column lookup\n\nupdated so each entry in the featureInfo.simpleProperties.columns only results in one Property being\nreturned.\n'}

In [26]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [27]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,ngageoint_opensphere,0000b245ec6ef0930251d1efab26a5229976c38b,Glenn Kitchell <kitchellg@wudn-kitchellg.udev....,1607457593,feat(featureinfo): improve column lookup\n\nup...

In [28]:
#mode a means append, so you have all your projects in the same file
yournetid='cfinley6'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github

# Notes:

While I am uncertain, I think I have the things that were asked for?  Also, only 9 of the 10 repos worked, one of them returned with an error.